# SQL-Based Analysis for Chinook database

## Connection

In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook.
%load_ext sql

# Establish a connection to a SQLite database file.
%sql sqlite:///chinook.db

'Connected: @chinook.db'

## Explore the database

In [85]:
%%sql
SELECT name FROM sqlite_master WHERE type='table';

 * sqlite:///chinook.db
Done.

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [84]:
%%sql
SELECT * FROM employees LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'Adams', 'Andrew', 'General Manager', None, '1962-02-18 00:00:00', '2002-08-14 00:00:00', '11120 Jasper Ave NW', 'Edmonton', 'AB', 'Canada', 'T5K 2N1', '+1 (780) 428-9482', '+1 (780) 428-3457', 'andrew@chinookcorp.com'),
 (2, 'Edwards', 'Nancy', 'Sales Manager', 1, '1958-12-08 00:00:00', '2002-05-01 00:00:00', '825 8 Ave SW', 'Calgary', 'AB', 'Canada', 'T2P 2T3', '+1 (403) 262-3443', '+1 (403) 262-3322', 'nancy@chinookcorp.com')]

In [83]:
%%sql
SELECT * FROM customers LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'Luís', 'Gonçalves', 'Embraer - Empresa Brasileira de Aeronáutica S.A.', 'Av. Brigadeiro Faria Lima, 2170', 'São José dos Campos', 'SP', 'Brazil', '12227-000', '+55 (12) 3923-5555', '+55 (12) 3923-5566', 'luisg@embraer.com.br', 3),
 (2, 'Leonie', 'Köhler', None, 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', '+49 0711 2842222', None, 'leonekohler@surfeu.de', 5)]

In [82]:
%%sql
SELECT * FROM albums LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'For Those About To Rock We Salute You', 1), (2, 'Balls to the Wall', 2)]

In [81]:
%%sql
SELECT * FROM playlists LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'Music'), (2, 'Movies')]

In [78]:
%%sql
SELECT * FROM playlist_track LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 3402), (1, 3389)]

In [77]:
%%sql
SELECT * FROM artists LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'AC/DC'), (2, 'Accept')]

In [76]:
%%sql
SELECT * FROM tracks LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'For Those About To Rock (We Salute You)', 1, 1, 1, 'Angus Young, Malcolm Young, Brian Johnson', 343719, 11170334, 0.99),
 (2, 'Balls to the Wall', 2, 2, 1, None, 342562, 5510424, 0.99)]

In [75]:
%%sql
SELECT * FROM media_types LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'MPEG audio file'), (2, 'Protected AAC audio file')]

In [74]:
%%sql
SELECT * FROM genres LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 'Rock'), (2, 'Jazz')]

In [55]:
%%sql
SELECT * FROM invoice_items LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 1, 2, 0.99, 1), (2, 1, 4, 0.99, 1)]

In [56]:
%%sql
SELECT * FROM invoices LIMIT 2;

 * sqlite:///chinook.db
Done.

[(1, 2, '2009-01-01 00:00:00', 'Theodor-Heuss-Straße 34', 'Stuttgart', None, 'Germany', '70174', 1.98),
 (2, 4, '2009-01-02 00:00:00', 'Ullevålsveien 14', 'Oslo', None, 'Norway', '0171', 3.96)]

## Answering key business questions

### top-selling products

In [54]:
%%sql
SELECT 
    tracks.Name AS Track,
    SUM(invoice_items.UnitPrice * invoice_items.Quantity) AS TrackRevenue
FROM 
    tracks
JOIN invoice_items ON invoice_items.TrackId = tracks.TrackId

GROUP BY tracks.Name
ORDER BY TrackRevenue DESC
LIMIT 10
;

 * sqlite:///chinook.db
Done.

[('The Trooper', 4.95),
 ('Walkabout', 3.98),
 ('The Woman King', 3.98),
 ('The Fix', 3.98),
 ('Pilot', 3.98),
 ("Phyllis's Wedding", 3.98),
 ('How to Stop an Exploding Man', 3.98),
 ('Hot Girl', 3.98),
 ('Gay Witch Hunt', 3.98),
 ('Branch Closing', 3.98)]

### the top 10 most sold tracks

In [53]:
%%sql
SELECT
    tracks.Name AS TrackName,
    artists.Name AS ArtistName,
    albums.Title AS AlbumTitle,
    COUNT(invoice_items.InvoiceLineId) AS TimesSold
FROM 
    tracks
JOIN invoice_items ON tracks.TrackId = invoice_items.TrackId
JOIN albums ON tracks.AlbumId = albums.AlbumId
JOIN artists ON albums.ArtistId = artists.ArtistId

GROUP BY tracks.TrackId
ORDER BY TimesSold DESC
LIMIT 10
;

 * sqlite:///chinook.db
Done.

[('Balls to the Wall', 'Accept', 'Balls to the Wall', 2),
 ('Inject The Venom', 'AC/DC', 'For Those About To Rock We Salute You', 2),
 ('Snowballed', 'AC/DC', 'For Those About To Rock We Salute You', 2),
 ('Overdose', 'AC/DC', 'Let There Be Rock', 2),
 ('Deuces Are Wild', 'Aerosmith', 'Big Ones', 2),
 ('Not The Doctor', 'Alanis Morissette', 'Jagged Little Pill', 2),
 ('Por Causa De Você', 'Antônio Carlos Jobim', 'Warner 25 Anos', 2),
 ('Welcome Home (Sanitarium)', 'Apocalyptica', 'Plays Metallica By Four Cellos', 2),
 ('Snowblind', 'Black Sabbath', 'Black Sabbath Vol. 4 (Remaster)', 2),
 ('Cornucopia', 'Black Sabbath', 'Black Sabbath Vol. 4 (Remaster)', 2)]

### revenue per region

In [52]:
%%sql
SELECT 
    customers.Country, 
    SUM(invoices.Total) AS Revenue
FROM 
    invoices
JOIN customers ON invoices.CustomerId = customers.CustomerId

GROUP BY customers.Country
ORDER BY Revenue DESC
;

 * sqlite:///chinook.db
Done.

[('USA', 523.06),
 ('Canada', 303.96),
 ('France', 195.1),
 ('Brazil', 190.1),
 ('Germany', 156.48),
 ('United Kingdom', 112.86),
 ('Czech Republic', 90.24),
 ('Portugal', 77.24),
 ('India', 75.26),
 ('Chile', 46.62),
 ('Ireland', 45.62),
 ('Hungary', 45.62),
 ('Austria', 42.62),
 ('Finland', 41.62),
 ('Netherlands', 40.62),
 ('Norway', 39.62),
 ('Sweden', 38.62),
 ('Spain', 37.62),
 ('Poland', 37.62),
 ('Italy', 37.62),
 ('Denmark', 37.62),
 ('Belgium', 37.62),
 ('Australia', 37.62),
 ('Argentina', 37.62)]

### monthly performance

In [68]:
%%sql
SELECT
    strftime('%Y-%m', invoices.InvoiceDate) AS Month,
    SUM(Total) AS Revenue,
    COUNT(InvoiceId) AS No_Of_Invoices
FROM invoices

GROUP BY Month
ORDER BY Month
;

 * sqlite:///chinook.db
Done.

[('2009-01', 35.64, 6),
 ('2009-02', 37.62, 7),
 ('2009-03', 37.62, 7),
 ('2009-04', 37.62, 7),
 ('2009-05', 37.62, 7),
 ('2009-06', 37.62, 7),
 ('2009-07', 37.62, 7),
 ('2009-08', 37.62, 7),
 ('2009-09', 37.62, 7),
 ('2009-10', 37.62, 7),
 ('2009-11', 37.62, 7),
 ('2009-12', 37.62, 7),
 ('2010-01', 52.62, 7),
 ('2010-02', 46.62, 7),
 ('2010-03', 44.62, 7),
 ('2010-04', 37.62, 7),
 ('2010-05', 37.62, 7),
 ('2010-06', 37.62, 7),
 ('2010-07', 37.62, 7),
 ('2010-08', 37.62, 7),
 ('2010-09', 36.63, 6),
 ('2010-10', 37.62, 7),
 ('2010-11', 37.62, 7),
 ('2010-12', 37.62, 7),
 ('2011-01', 37.62, 7),
 ('2011-02', 37.62, 7),
 ('2011-03', 37.62, 7),
 ('2011-04', 51.62, 7),
 ('2011-05', 42.62, 7),
 ('2011-06', 50.62, 7),
 ('2011-07', 37.62, 7),
 ('2011-08', 37.62, 7),
 ('2011-09', 37.62, 7),
 ('2011-10', 37.62, 7),
 ('2011-11', 23.76, 6),
 ('2011-12', 37.62, 7),
 ('2012-01', 37.62, 7),
 ('2012-02', 37.62, 7),
 ('2012-03', 37.62, 7),
 ('2012-04', 37.62, 7),
 ('2012-05', 37.62, 7),
 ('2012-06', 37.62, 7),
 ('2012-07', 39.62, 7),
 ('2012-08', 47.62, 7),
 ('2012-09', 46.71, 6),
 ('2012-10', 42.62, 7),
 ('2012-11', 37.62, 7),
 ('2012-12', 37.62, 7),
 ('2013-01', 37.62, 7),
 ('2013-02', 27.72, 5),
 ('2013-03', 37.62, 7),
 ('2013-04', 33.66, 5),
 ('2013-05', 37.62, 7),
 ('2013-06', 37.62, 7),
 ('2013-07', 37.62, 7),
 ('2013-08', 37.62, 7),
 ('2013-09', 37.62, 7),
 ('2013-10', 37.62, 7),
 ('2013-11', 49.62, 7),
 ('2013-12', 38.62, 7)]

### rank top 3 tracks per genre for best-seller

In [73]:
%%sql
WITH TrackSales AS (
    SELECT
        g.Name AS GenreName,
        t.Name AS TrackName,
        COUNT(il.TrackId) AS TimesSold
    FROM 
        invoice_items il
    JOIN tracks t ON il.TrackId = t.TrackId
    JOIN genres g ON t.GenreId = g.GenreId

    GROUP BY g.Name, t.Name
),
RankedSales AS (
    SELECT
        GenreName,
        TrackName,
        TimesSold,
        RANK() OVER (PARTITION BY GenreName ORDER BY TimesSold DESC) AS SalesRank
    FROM 
        TrackSales
)
SELECT
    GenreName,
    TrackName,
    TimesSold,
    SalesRank
FROM 
    RankedSales
WHERE SalesRank <= 3;

 * sqlite:///chinook.db
Done.

[('Alternative', 'All Night Thing', 1, 1),
 ('Alternative', 'Billie Jean', 1, 1),
 ('Alternative', 'Call Me a Dog', 1, 1),
 ('Alternative', 'Disappearing Act', 1, 1),
 ('Alternative', 'Four Walled World', 1, 1),
 ('Alternative', 'Moth', 1, 1),
 ('Alternative', 'Safe and Sound', 1, 1),
 ('Alternative', 'Say Hello 2 Heaven', 1, 1),
 ('Alternative', 'Scar On the Sky', 1, 1),
 ('Alternative', 'Shape of Things to Come', 1, 1),
 ('Alternative', 'Show Me How to Live (Live at the Quart Festival)', 1, 1),
 ('Alternative', 'Slowness', 1, 1),
 ('Alternative', 'Sound of a Gun', 1, 1),
 ('Alternative', 'Until We Fall', 1, 1),
 ('Alternative & Punk', 'Release', 3, 1),
 ('Alternative & Punk', 'A Melhor Forma', 2, 2),
 ('Alternative & Punk', 'Ando Meio Desligado', 2, 2),
 ('Alternative & Punk', 'Babylon', 2, 2),
 ('Alternative & Punk', 'Basket Case', 2, 2),
 ('Alternative & Punk', 'Big Wave', 2, 2),
 ('Alternative & Punk', 'Bowels Of The Devil', 2, 2),
 ('Alternative & Punk', 'Bullet With Butterfly Wings', 2, 2),
 ('Alternative & Punk', 'Cabeça Dinossauro', 2, 2),
 ('Alternative & Punk', 'Caffeine', 2, 2),
 ('Alternative & Punk', 'Cherub Rock', 2, 2),
 ('Alternative & Punk', 'Comida', 2, 2),
 ('Alternative & Punk', 'Country Feedback', 2, 2),
 ('Alternative & Punk', 'Easy', 2, 2),
 ('Alternative & Punk', 'Esporrei Na Manivela', 2, 2),
 ('Alternative & Punk', 'Fall On Me', 2, 2),
 ('Alternative & Punk', 'Get Up', 2, 2),
 ('Alternative & Punk', 'Give Me Novacaine', 2, 2),
 ('Alternative & Punk', 'Gyroscope', 2, 2),
 ('Alternative & Punk', 'Heaven Coming Down', 2, 2),
 ('Alternative & Punk', 'Holiday', 2, 2),
 ('Alternative & Punk', 'I Believe', 2, 2),
 ('Alternative & Punk', 'Last Cup Of Sorrow', 2, 2),
 ('Alternative & Punk', 'Lugar Nenhum', 2, 2),
 ('Alternative & Punk', 'Midlife Crisis', 2, 2),
 ('Alternative & Punk', 'Nice Guys Finish Last', 2, 2),
 ('Alternative & Punk', 'O Pulso', 2, 2),
 ('Alternative & Punk', 'Radio Song', 2, 2),
 ('Alternative & Punk', 'Real Love', 2, 2),
 ('Alternative & Punk', 'Saturnine', 2, 2),
 ('Alternative & Punk', 'She Loves Me Not', 2, 2),
 ('Alternative & Punk', 'So Central Rain', 2, 2),
 ('Alternative & Punk', 'Take It Or Leave It', 2, 2),
 ('Alternative & Punk', 'Times Like These', 2, 2),
 ('Alternative & Punk', 'Toda Cor', 2, 2),
 ('Alternative & Punk', 'Train In Vain', 2, 2),
 ('Alternative & Punk', 'Under The Bridge', 2, 2),
 ('Alternative & Punk', 'Untitled', 2, 2),
 ('Alternative & Punk', 'Voodoo', 2, 2),
 ('Alternative & Punk', 'Waiting', 2, 2),
 ('Alternative & Punk', 'Whatsername', 2, 2),
 ('Alternative & Punk', 'When I Come Around', 2, 2),
 ('Blues', 'Lay Down Sally', 2, 1),
 ('Blues', 'Layla', 2, 1),
 ('Blues', 'Leave My Girl Alone', 2, 1),
 ('Blues', 'Let Me Love You Baby', 2, 1),
 ('Blues', 'Lonely Stranger', 2, 1),
 ('Blues', 'Midnight From The Inside Out', 2, 1),
 ('Blues', 'Promises', 2, 1),
 ('Blues', 'Sunshine Of Your Love', 2, 1),
 ('Blues', 'Title Song', 2, 1),
 ('Blues', 'Travis Walk', 2, 1),
 ('Blues', 'When My Left Eye Jumps', 2, 1),
 ('Bossa Nova', 'Onde Anda Você', 2, 1),
 ('Bossa Nova', 'Berimbau', 1, 2),
 ('Bossa Nova', 'Canto De Ossanha', 1, 2),
 ('Bossa Nova', 'Carta Ao Tom 74', 1, 2),
 ('Bossa Nova', 'Como É Duro Trabalhar', 1, 2),
 ('Bossa Nova', 'Deixa', 1, 2),
 ('Bossa Nova', 'Formosa', 1, 2),
 ('Bossa Nova', 'Minha Namorada', 1, 2),
 ('Bossa Nova', 'Por Que Será', 1, 2),
 ('Bossa Nova', 'Pot-Pourri N.º 2', 1, 2),
 ('Bossa Nova', 'Pot-Pourri N.º 4', 1, 2),
 ('Bossa Nova', 'Pot-Pourri N.º 5', 1, 2),
 ('Bossa Nova', 'Samba Da Volta', 1, 2),
 ('Bossa Nova', 'Samba Em Prelúdio', 1, 2),
 ('Classical', 'Music for the Funeral of Queen Mary: VI. "Thou Knowest, Lord, the Secrets of Our Hearts"', 2, 1),
 ('Classical', "Scheherazade, Op. 35: I. The Sea and Sindbad's Ship", 2, 1),
 ('Classical', 'String Quartet No. 12 in C Minor, D. 703 "Quartettsatz": II. Andante - Allegro assai', 2, 1),
 ('Classical', 'Suite No. 3 in D, BWV 1068: III. Gavotte I & II', 2, 1),
 ('Classical', "Symphonie Fantastique, Op. 14: V. Songe d'une nuit du sabbat", 2, 1),
 ('Comedy', "Phyllis's Wedding", 2, 1),
 ('Comedy', 'A Benihana Christmas, Pts. 1 & 2', 1, 2),
 ('Comedy', 'Back from Vacation', 1, 2),
 ('Comedy', 'Branch Closing', 1, 2),
 ('Comedy', "Producer's Cut: The Return", 1, 2),
 ('Comedy', 'Safety Training', 1, 2),
 ('Comedy', 'The Convict', 1, 2),
 ('Comedy', 'The Job', 1, 2),
 ('Drama', 'How to Stop an Exploding Man', 2, 1),
 ('Drama', 'The Fix', 2, 1),
 ('Drama', 'Better Halves', 1, 3),
 ('Drama', 'Catch-22', 1, 3),
 ('Drama', 'Company Man', 1, 3),
 ('Drama', 'Distractions', 1, 3),
 ('Drama', 'Enter 77', 1, 3),
 ('Drama', 'Exposé', 1, 3),
 ('Drama', 'Fire + Water', 1, 3),
 ('Drama', 'Live Together, Die Alone, Pt. 1', 1, 3),
 ('Drama', 'Lost Survival Guide', 1, 3),
 ('Drama', 'One Giant Leap', 1, 3),
 ('Drama', 'Par Avion', 1, 3),
 ('Drama', 'Parasite', 1, 3),
 ('Drama', 'Past, Present, and Future', 1, 3),
 ('Drama', 'Seven Minutes to Midnight', 1, 3),
 ('Drama', 'Something Nice Back Home', 1, 3),
 ('Drama', 'Stranger In a Strange Land', 1, 3),
 ('Drama', 'The Beginning of the End', 1, 3),
 ('Drama', 'The Economist', 1, 3),
 ('Drama', 'The Glass Ballerina', 1, 3),
 ('Drama', 'The Hard Part', 1, 3),
 ('Drama', 'The Man Behind the Curtain', 1, 3),
 ('Drama', 'The Whole Truth', 1, 3),
 ('Drama', "There's No Place Like Home, Pt. 3", 1, 3),
 ('Drama', 'Through a Looking Glass', 1, 3),
 ('Drama', 'Through the Looking Glass, Pt. 1', 1, 3),
 ('Easy Listening', 'Bad, Bad Leroy Brown', 1, 1),
 ('Easy Listening', 'Come Fly With Me', 1, 1),
 ('Easy Listening', 'Fly Me To The Moon', 1, 1),
 ('Easy Listening', 'I Get A Kick Out Of You', 1, 1),
 ('Easy Listening', 'It Was A Very Good Year', 1, 1),
 ('Easy Listening', 'Mack The Knife', 1, 1),
 ('Easy Listening', 'My Kind Of Town', 1, 1),
 ('Easy Listening', 'New York, New York', 1, 1),
 ('Easy Listening', 'Summer Love', 1, 1),
 ('Easy Listening', 'What Now My Love', 1, 1),
 ('Electronica/Dance', 'Light Years', 2, 1),
 ('Electronica/Dance', 'Armadura', 1, 2),
 ('Electronica/Dance', 'Chapa o Coco', 1, 2),
 ('Electronica/Dance', 'Chega no Suingue', 1, 2),
 ('Electronica/Dance', 'Funk de Bamba', 1, 2),
 ('Electronica/Dance', 'Instinto Colectivo', 1, 2),
 ('Electronica/Dance', 'Journey To Arnhemland', 1, 2),
 ('Electronica/Dance', 'Manifest Destiny', 1, 2),
 ('Electronica/Dance', 'Morning Glory', 1, 2),
 ('Electronica/Dance', 'Todo o Carnaval tem seu Fim', 1, 2),
 ('Electronica/Dance', 'Um Lugar ao Sol', 1, 2),
 ('Heavy Metal', 'Age Of Innocence', 1, 1),
 ('Heavy Metal', 'Another Life', 1, 1),
 ('Heavy Metal', 'Dance Of Death', 1, 1),
 ('Heavy Metal', 'Die With Your Boots On', 1, 1),
 ('Heavy Metal', 'Drifter', 1, 1),
 ('Heavy Metal', 'Face In The Sand', 1, 1),
 ('Heavy Metal', 'Gates Of Tomorrow', 1, 1),
 ('Heavy Metal', 'Genghis Khan', 1, 1),
 ('Heavy Metal', 'Phantom Of The Opera', 1, 1),
 ('Heavy Metal', 'Purgatory', 1, 1),
 ('Heavy Metal', 'The Ides Of March', 1, 1),
 ('Heavy Metal', 'Wildest Dreams', 1, 1),
 ('Hip Hop/Rap', 'Nega Do Cabelo Duro', 2, 1),
 ('Hip Hop/Rap', 'Rappers Reais', 2, 1),
 ('Hip Hop/Rap', 'Bossa', 1, 3),
 ('Hip Hop/Rap', 'Commercial 2', 1, 3),
 ('Hip Hop/Rap', 'Danny Boy, Danny Boy', 1, 3),
 ('Hip Hop/Rap', 'Feel It', 1, 3),
 ('Hip Hop/Rap', "Guess Who's Back", 1, 3),
 ('Hip Hop/Rap', 'Hemp Family', 1, 3),
 ('Hip Hop/Rap', 'Hip Hop Rio', 1, 3),
 ('Hip Hop/Rap', 'O Bicho Tá Pregando', 1, 3),
 ('Hip Hop/Rap', 'One For The Road', 1, 3),
 ('Hip Hop/Rap', 'Put Your Head Out', 1, 3),
 ('Hip Hop/Rap', 'Salutations', 1, 3),
 ('Hip Hop/Rap', 'Se Liga', 1, 3),
 ('Hip Hop/Rap', "Top O' The Morning To Ya", 1, 3),
 ('Jazz', 'Blue Rythm Fantasy', 2, 1),
 ('Jazz', "Don't Take Your Love From Me", 2, 1),
 ('Jazz', 'Drum Boogie', 2, 1),
 ('Jazz', 'End Of Romanticism', 2, 1),
 ('Jazz', 'J Squared', 2, 1),
 ('Jazz', "L'Arc En Ciel De Miles", 2, 1),
 ('Jazz', 'Lamento De Carnaval', 2, 1),
 ('Jazz', 'Lemon Drop', 2, 1),
 ('Jazz', 'Por Causa De Você', 2, 1),
 ('Jazz', 'Starburst', 2, 1),
 ('Jazz', 'Surrender', 2, 1),
 ('Jazz', 'The Duke', 2, 1),
 ('Latin', 'Brasil', 3, 1),
 ('Latin', 'Linha Do Equador', 3, 1),
 ('Latin', 'Selvagem', 3, 1),
 ('Metal', '2 Minutes To Midnight', 3, 1),
 ('Metal', 'Can I Play With Madness', 3, 1),
 ('Metal', 'The Trooper', 3, 1),
 ('Metal', 'Welcome Home (Sanitarium)', 3, 1),
 ('Metal', 'Where Eagles Dare', 3, 1),
 ('Pop', 'Beautiful Boy', 2, 1),
 ('Pop', 'Gimme Some Truth', 2, 1),
 ('Pop', 'Give Peace a Chance', 2, 1),
 ('Pop', 'Imagine', 2, 1),
 ('R&B/Soul', 'Abraham, Martin And John', 2, 1),
 ('R&B/Soul', 'Hey America', 2, 1),
 ('R&B/Soul', 'Rehab', 2, 1),
 ('R&B/Soul', 'Save The Children', 2, 1),
 ('Reggae', 'A Cor Do Sol', 2, 1),
 ('Reggae', "C'est La Vie", 2, 1),
 ('Reggae', 'Firmamento', 2, 1),
 ('Reggae', 'Onde Você Mora?', 2, 1),
 ('Rock', 'Eruption', 4, 1),
 ('Rock', 'Sure Know Something', 4, 1),
 ('Rock', 'Dazed and Confused', 3, 3),
 ('Rock', 'Hallowed Be Thy Name', 3, 3),
 ('Rock', 'Plaster Caster', 3, 3),
 ('Rock', 'Sanctuary', 3, 3),
 ('Rock', 'Stairway To Heaven', 3, 3),
 ('Rock', 'Sweetest Thing', 3, 3),
 ('Rock', 'The Number Of The Beast', 3, 3),
 ('Rock And Roll', "C'Mon Everybody", 1, 1),
 ('Rock And Roll', 'Carol', 1, 1),
 ('Rock And Roll', 'Good Golly Miss Molly', 1, 1),
 ('Rock And Roll', 'Long Tall Sally', 1, 1),
 ('Rock And Roll', 'Money', 1, 1),
 ('Rock And Roll', "Rock 'N' Roll Music", 1, 1),
 ('Sci Fi & Fantasy', "Baltar's Escape", 1, 1),
 ('Sci Fi & Fantasy', 'Battlestar Galactica, Pt. 1', 1, 1),
 ('Sci Fi & Fantasy', 'Battlestar Galactica, Pt. 2', 1, 1),
 ('Sci Fi & Fantasy', 'Crossroads, Pt. 1', 1, 1),
 ('Sci Fi & Fantasy', 'Crossroads, Pt. 2', 1, 1),
 ('Sci Fi & Fantasy', 'Experiment In Terra', 1, 1),
 ('Sci Fi & Fantasy', 'Greetings from Earth, Pt. 1', 1, 1),
 ('Sci Fi & Fantasy', 'Greetings from Earth, Pt. 2', 1, 1),
 ('Sci Fi & Fantasy', 'Lost Planet of the Gods, Pt. 1', 1, 1),
 ('Sci Fi & Fantasy', 'Lost Planet of the Gods, Pt. 2', 1, 1),
 ('Sci Fi & Fantasy', 'Take the Celestra', 1, 1),
 ('Sci Fi & Fantasy', 'The Gun On Ice Planet Zero, Pt. 1', 1, 1),
 ('Sci Fi & Fantasy', 'The Gun On Ice Planet Zero, Pt. 2', 1, 1),
 ('Sci Fi & Fantasy', 'The Hand of God', 1, 1),
 ('Sci Fi & Fantasy', 'The Living Legend, Pt. 1', 1, 1),
 ('Sci Fi & Fantasy', 'The Living Legend, Pt. 2', 1, 1),
 ('Sci Fi & Fantasy', 'The Long Patrol', 1, 1),
 ('Sci Fi & Fantasy', 'The Lost Warrior', 1, 1),
 ('Sci Fi & Fantasy', 'The Magnificent Warriors', 1, 1),
 ('Sci Fi & Fantasy', 'War of the Gods, Pt. 2', 1, 1),
 ('Science Fiction', 'The Woman King', 2, 1),
 ('Science Fiction', 'A Day In the Life', 1, 2),
 ('Science Fiction', 'Hero', 1, 2),
 ('Science Fiction', 'The Passage', 1, 2),
 ('Science Fiction', 'Unfinished Business', 1, 2),
 ('Soundtrack', 'Plot 180', 2, 1),
 ('Soundtrack', 'Assum Preto', 1, 2),
 ('Soundtrack', 'Beach Sequence', 1, 2),
 ('Soundtrack', 'Camisa Verde 2001', 1, 2),
 ('Soundtrack', 'Esperando Na Janela', 1, 2),
 ('Soundtrack', 'Gavioes 2001', 1, 2),
 ('Soundtrack', 'Ipiranga 2001', 1, 2),
 ('Soundtrack', 'Ito Okashi', 1, 2),
 ('Soundtrack', 'Juazeiro', 1, 2),
 ('Soundtrack', 'Lamento Sertanejo', 1, 2),
 ('Soundtrack', 'Leandro De Itaquera 2001', 1, 2),
 ('Soundtrack', 'Miss Sarajevo', 1, 2),
 ('Soundtrack', 'Morro Da Casa Verde 2001', 1, 2),
 ('Soundtrack', 'Pau-De-Arara', 1, 2),
 ('Soundtrack', 'Slug', 1, 2),
 ('Soundtrack', 'Theme From The Swan', 1, 2),
 ('Soundtrack', 'United Colours', 1, 2),
 ('Soundtrack', 'X-9 2001', 1, 2),
 ('Soundtrack', 'Your Blue Room', 1, 2),
 ('TV Shows', 'Gay Witch Hunt', 2, 1),
 ('TV Shows', 'Hot Girl', 2, 1),
 ('TV Shows', 'Pilot', 2, 1),
 ('TV Shows', 'Walkabout', 2, 1),
 ('World', 'A Moça e a Chuva', 1, 1),
 ('World', 'Aos Leões', 1, 1),
 ('World', 'Cafezinho', 1, 1),
 ('World', 'Demorou!', 1, 1),
 ('World', 'Din Din Wo (Little Child)', 1, 1),
 ('World', 'Enquanto O Dia Não Vem', 1, 1),
 ('World', 'Equinocio', 1, 1),
 ('World', 'Já Foi', 1, 1),
 ('World', 'No Futuro', 1, 1),
 ('World', 'O Que Vai Em Meu Coração', 1, 1),
 ('World', 'Papelão', 1, 1),
 ('World', 'Voce Inteira', 1, 1),
 ('World', 'É Fogo', 1, 1)]